---PART A:
INSERT INTO Village (VID, Name, CityID) VALUES
(101, 'Raiya', 1),
(102, 'Madhapar', 1),
(103, 'Dodka', 3),
(104, 'Falla', 4),
(105, 'Bhesan', 5),
(106, 'Dhoraji', 5);

--1. Display all the villages of Rajkot city. 
SELECT VILLAGE.NAME 
FROM CITY JOIN VILLAGE
ON CITY.CITYID = VILLAGE.CITYID
WHERE CITY.NAME = 'RAJKOT'
--2. Display city along with their villages & pin code.
SELECT CITY.NAME , VILLAGE.NAME , CITY.PINCODE
FROM CITY LEFT OUTER JOIN VILLAGE
ON CITY.CITYID = VILLAGE.CITYID
--3. Display the city having more than one village.
SELECT CITY.NAME , COUNT(VILLAGE.VID)
FROM CITY LEFT OUTER JOIN VILLAGE
ON CITY.CITYID = VILLAGE.CITYID
GROUP BY CITY.NAME
HAVING COUNT(VILLAGE.VID) > 1
--4. Display the city having no village.
SELECT CITY.NAME
FROM CITY LEFT OUTER JOIN VILLAGE
ON CITY.CITYID = VILLAGE.CITYID
GROUP BY CITY.NAME
HAVING COUNT(VILLAGE.VID) = 0
--5. Count the total number of villages in each city.
SELECT CITY.NAME , COUNT(VILLAGE.VID) AS [VILLAGE]
FROM CITY LEFT OUTER JOIN VILLAGE
ON CITY.CITYID = VILLAGE.CITYID
GROUP BY CITY.NAME
--6. Count the number of cities having more than one village.
SELECT COUNT(CITY.NAME)
FROM CITY JOIN VILLAGE
ON CITY.CITYID = VILLAGE.CITYID
GROUP BY CITY.NAME
HAVING COUNT(VILLAGE.VID) > 1


CREATE TABLE STU_MASTER(
	RNO INT PRIMARY KEY,
	NAME VARCHAR(20),
	BRANCH VARCHAR(20) DEFAULT 'GENERAL',
	SPI DECIMAL(8,2) CHECK(SPI<=10) ,
	BKLOG INT CHECK(BKLOG>=0)
)
INSERT INTO STU_MASTER VALUES
(101, 'Raju', 'CE', 8.80, 0),
(102 ,'Amit' ,'CE',2.20 ,3),
(103, 'Sanjay', 'ME', 1.50, 6),
(104, 'Neha', 'EC', 7.65, 0),
(105 ,'Meera' ,'EE' ,5.52 ,2),
(106, 'Mahesh', NULL , 4.50, 3)

--4. Try to update SPI of Raju from 8.80 to 12.
UPDATE STU_MASTER SET SPI = 12 WHERE NAME ='RAJU'
--5. Try to update Bklog of Neha from 0 to -1.
UPDATE STU_MASTER SET BKLOG = -1 WHERE NAME ='NEHA'



