SELECT TOP 50 PERCENT* FROM BORROW
SELECT TOP 10 PERCENT* FROM DEPOSIT
SELECT TOP 25 PERCENT* FROM DEPOSIT WHERE AMOUNT>5000
SELECT TOP 10 PERCENT AMOUNT FROM BORROW
SELECT DISTINCT CNAME,CITY FROM CUSTOMER
SELECT*,(AMOUNT+(AMOUNT*0.1)) AS AMOUNT FROM BORROW
SELECT* FROM BORROW WHERE (LOANNO%2)=0
SELECT* FROM BORROW WHERE (LOANNO%2)!=0
