SELECT*FROM DEPOSIT
SELECT*FROM BRANCH
SELECT*FROM DEPOSIT
SELECT ACTNO,CNAME,AMOUNT FROM DEPOSIT
SELECT LOANNO,AMOUNT FROM BORROW
SELECT*FROM BORROW WHERE BNAME ='ANDHERI'
SELECT ACTNO,AMOUNT FROM DEPOSIT WHERE ACTNO=106
SELECT CNAME FROM BORROW WHERE AMOUNT>5000
SELECT CNAME FROM DEPOSIT WHERE ADATE > '1-DEC-1996'
SELECT CNAME FROM DEPOSIT WHERE ACTNO>105
SELECT CNAME FROM CUSTOMER WHERE CITY='NAGPUR' OR CITY='DELHI'
SELECT CNAME FROM DEPOSIT WHERE AMOUNT>4000 AND ACTNO<105
SELECT*FROM BORROW WHERE AMOUNT>=3000 AND AMOUNT<=8000
SELECT*FROM BORROW WHERE AMOUNT BETWEEN 3000 AND 8000
SELECT*FROM DEPOSIT WHERE BNAME <> 'ANDHERI'
SELECT ACTNO,CNAME,AMOUNT FROM DEPOSIT WHERE BNAME IN ('AJNI','KAROLBAGH','M.G.ROAD') AND ACTNO<104