CREATE TABLE EMPLOYEE(
	NAME VARCHAR(50),
	CITY VARCHAR(20),
	AGE INT
	)
	SELECT * FROM EMPLOYEE
INSERT INTO EMPLOYEE
VALUES('Jay Patel', 'Rajkot', 30 ),
	('Rahul Dave','Baroda', 35) ,
	('Jeet Patel', 'Surat', 31) ,
	('Vijay Raval','Rajkot',30)
	
	SELECT* INTO EMPLOYEE_DETAIL FROM EMPLOYEE
	SELECT* FROM EMPLOYEE_DETAIL
	SELECT NAME,CITY INTO EMPLOYEE_DATA FROM EMPLOYEE WHERE 'J' = 'S'
	SELECT* INTO EMPLOYEE_INFO FROM EMPLOYEE WHERE 1=0
