CREATE TABLE STUDENT_DETAIL(
 ENROLLMENT_NO VARCHAR(20),
 NAME VARCHAR(25),
 CPI DECIMAL(5,2),
 BIRTHDATE DATETIME
 )
 --Add two more columns City VARCHAR (20) (Not null) and Backlog INT (Null)
 ALTER TABLE STUDENT_DETAIL ADD CITY VARCHAR(20) NOT NULL,BACKLOG INT NULL
 --Change the size of NAME column of student_detail from VARCHAR (25) to VARCHAR (35).
 ALTER TABLE STUDENT_DETAIL ALTER COLUMN NAME VARCHAR(35)
 --Change the data type DECIMAL to INT in CPI Column
 ALTER TABLE STUDENT_DETAIL ALTER COLUMN CPI INT
 --Rename Column Enrollment_No to ENO
 SP_RENAME 'STUDENT_DETAIL.ENROLLMENT_NO' ,ENO 
 --Delete Column City from the student_detail table.
 ALTER TABLE STUDENT_DETAIL DROP COLUMN CITY
 --Change name of table student_detail to STUDENT_MASTER
 SP_RENAME 'STUDENT_DETAIL',STUDENT_MASTER