--Rename Column ADATE to AOPENDATE OF DEPOSIT_DETAIL table
SP_RENAME 'DEPOSIT_DETAIL.ADATE', AOPENDATE
--Delete Column AOPENDATE from the DEPOSIT_DETAIL table.
ALTER TABLE DEPOSIT_DETAIL DROP COLUMN AOPENDATE
--Rename Column CNAME to CustomerName.
SP_RENAME 'DEPOSIT_DETAIL.CNAME',CUSTOMERNAME